outiltheque/loans/urls.py
from django.urls import path
from . import views
from .views import  LoanDetailView
urlpatterns = [
    path('', views.lend_home, name='lend-home'),
    
    path('loan/new/<int:tool_id>/', views.loans_requestCreation , name='loan-create'),
    path('loan/<int:pk>/', LoanDetailView.as_view(), name='loan-detail'),
    path('loan/<int:pk>/accept/', views.loan_accept, name='loan-accept'),
    path('loan/<int:pk>/complete/', views.loan_complete, name='loan-complete'),
    path('loan/score/<int:user_id>/<int:loan_id>/', views.loan_score, name='loan-score'),

    path('borrow', views.borrow_home, name='borrow-home'),
    path('borrow/<int:pk>/', views.borrow_detail, name='borrow-detail'),
    path('borrow/<int:pk>/retrieve', views.borrow_retrieve, name='borrow-retrieve'),
    path('borrow/<int:pk>/returned', views.borrow_returned, name='borrow-returned'),
    path('borrow/score/<int:user_id>/<int:loan_id>/', views.borrow_score, name='borrow-score')

  
] 

outiltheque/outiltheque/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toolbox.urls')),
    path('loans/', include('loans.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html') , name='logout'),
    path('profile/', include('users.urls')),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

outiltheque/toolbox/urls.py
from django.urls import path
from .import views
from .views import ToolListView, ToolDetailView, ToolCreateView, ToolUpdateView, ToolDeleteView, UserToolListView

urlpatterns = [
    path('', ToolListView.as_view(), name='toolbox-home'),
    path('search/', views.tools_filter, name='tool-filter'),
    path('tool/<int:pk>/', ToolDetailView.as_view(), name='tool-detail'),
    path('tool/new/', ToolCreateView.as_view(), name='tool-create'),
    path('tool/<int:pk>/update/', ToolUpdateView.as_view(), name='tool-update'),
    path('tool/<int:pk>/delete/', ToolDeleteView.as_view(), name='tool-delete'),
    path('user/<str:username>', UserToolListView.as_view(), name='user-tools'),
    
] 

outiltheque/toolbox/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image

# Create your models here.
class Tool(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date_published = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='tool_pics')
    STATE_OF_USE = [
    ('New', 'Comme neuf'),
    ('Medium', 'Moyen'),
    ('Old', 'Usé'),
    ]
    state_of_use = models.CharField(max_length=100, choices=STATE_OF_USE, default='Medium')

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)  

    def get_absolute_url(self):
        return reverse('tool-detail', kwargs={'pk': self.pk})

    def short_desc(self):
            if len(self.description) > 50:
                return self.description[:50] + "..."
            else:
                return self.description

outiltheque/toolbox/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from .models import Tool
from django.contrib.auth.models import User
from django.views.generic import (ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .filters import ToolFilter
# Create your views here.


def home(request):

    tools = Tool.objects.all()
    context = {
        'tools' : tools
    }
    return render(request, 'toolbox/toolbox_home.html', context)


def tools_filter(request):
    tools = Tool.objects.all()
    tools_count = tools.count()
    tools_filter = ToolFilter(request.GET, queryset = tools)
    tools = tools_filter.qs

    context = {
        'tools' : tools,
        'tools_count': tools_count,
        'tools_filter' :  tools_filter
    }
    return render(request, 'toolbox/toolbox_filter.html', context)



class ToolListView(ListView):
    model = Tool
    template_name = 'toolbox/toolbox_home.html'
    context_object_name = 'tools'

    
class ToolDetailView(DetailView):
    model = Tool


class ToolCreateView(LoginRequiredMixin, CreateView):
    model = Tool
    fields = ['title', 'description', 'state_of_use', 'image']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class ToolUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Tool
    fields = ['title', 'description', 'state_of_use', 'image']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        tool = self.get_object()
        if self.request.user == tool.owner:
            return True
        return False

class ToolDeleteView(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = Tool
    success_url = '/'
    def test_func(self):
        tool = self.get_object()       
        if self.request.user == tool.owner:
            return True
        return False


class UserToolListView(ListView):
    model = Tool
    template_name = 'toolbox/user_tools.html'
    context_object_name = 'tools'

    

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Tool.objects.filter(owner=user)

outiltheque/toolbox/templates/toolbox/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%static 'toolbox/main.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'admin/css/forms.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'admin/css/widget.css'%}">

  </head>
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'toolbox-home' %}">Outiltheque</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'toolbox-home' %}">Home</a>
                <a class="nav-item nav-link btn btn-info btn-sm mt-1 mb-1" href="{% url 'tool-filter' %}">Search</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link btn btn-info btn-sm mt-1 mb-1" href="{% url 'tool-create' %}">New Tool</a>
                  
                  <a class="nav-item nav-link" href="{% url 'profile' %}">{{user.username}}</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>



    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock content%}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Toolbox</h3>
              <p class='text-muted'> 
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Messages</li>
                  <li class="list-group-item list-group-item-light"><a href="#">Mes outils</a></li>
                  <li class="list-group-item list-group-item-light"><a href="{% url 'lend-home' %}">Mes prêts</a></li>
                  <li class="list-group-item list-group-item-light"><a href="{% url 'borrow-home' %}"> Mes emprunts</a></li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>


      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

outiltheque/toolbox/templates/toolbox/tool_confirm_delete.html
{%extends 'toolbox/base.html'%}

{%block content%}
<div class="content-section">
    <form method="POST">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete tool</legend>
            <h2>are you sure you want to delete the tool "{{object.title}}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit"> Delete </button>
            <a class="btn btn-outline-info" href="{%url 'tool-detail' object.id %}"> Cancel </a>
        </div>
    </form>

</div>
{%endblock content%}

outiltheque/toolbox/templates/toolbox/tool_detail.html
{%extends 'toolbox/base.html'%}

{%block content%}

        <h2>Outil</h2>
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{object.owner.profile.image.url}}">
            <div class="madia-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-profile' object.owner.id%}"> {{object.owner}} </a>
                    {% if object.owner == user %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tool-update' object.id %}">Update</a>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'tool-delete' object.id %}">Delete</a>
                        </div>
                        
                    {% endif %}
                </div>
                <h2 class="article-title"> {{object.title}} </h2>
                <small class="text-muted"> Etat : {{object.get_state_of_use_display}}</small>
                <p class="article-content"> {{object.description}} </p>
            </div>

        </article>
        <h2>Photos</h2>
        <article class="media content-section">
           <img src="{{object.image.url}}">
        </article>

        {% if object.owner != user %}
        <a class="btn btn-outline-info" href="{% url 'loan-create' object.id %}"> Demande de pret </a>
        {% endif %}
    {%endblock content%}

outiltheque/toolbox/templates/toolbox/tool_form.html
{%extends 'toolbox/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Tool</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit"> Save </button>
        </div>
    </form>

</div>
{%endblock content%}

outiltheque/toolbox/templates/toolbox/toolbox_filter.html
{%extends 'toolbox/base.html'%}
{% load crispy_forms_tags %}
{%block content%}


    <h3>Les outils près de chez vous</h3>
    <div class="content-section">
        <form method="GET">
            {{tools_filter.form}}
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
    </div>
    {%for tool in tools%}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{tool.owner.profile.image.url}}">
            <div class="madia-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{%url 'user-profile' tool.owner.id %}"> {{tool.owner}} </a>
                    <small class="text-muted">{{ tool.date_published|date:"d F Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'tool-detail' tool.id %}"> {{tool.title}} </a> </h2>
                <small class="text-muted"> Etat : {{tool.get_state_of_use_display}}</small>
                <p class="article-content"> {{tool.description}} </p>
            </div>
        </article>
    {%endfor%}
{%endblock content%}

outiltheque/toolbox/templates/toolbox/toolbox_home.html
{%extends 'toolbox/base.html'%}



{%block content%}

    <h3>Les outils près de chez vous</h3>

  


<!-- 
    {%for tool in tools%}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{tool.owner.profile.image.url}}">
            <div class="madia-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{%url 'user-tools' tool.owner.username %}"> {{tool.owner}} </a>
                    <small class="text-muted">{{ tool.date_published|date:"d F Y" }}</small>
                  
                </div>
                <h2><a class="article-title" href="{% url 'tool-detail' tool.id %}"> {{tool.title}} </a> </h2>
                <small class="text-muted"> Etat : {{tool.get_state_of_use_display}}</small>
                <p class="article-content"> {{tool.description}} </p>
                <img src="{{tool.image.url}}">
            </div>
        </article>
    {%endfor%} 
-->
<div class="container">
    <div class="row">
        {%for tool in tools%}
        <div class="col-sm">
            <div class="card">
                <a href="{% url 'tool-detail' tool.id %}">

                    <!-- Image à la une -->
                    <div class="card-image"><img src="{{tool.image.url}}" alt="tool" /></div>
                    <!-- Fin de l'image à la une -->
            
                    <!-- Corp de notre carte -->
                    <div class="card-body">
                        <!-- Date de publication de l'article-->
                        <div class="card-date">
                            <time>{{ tool.date_published|date:"d F Y" }}</time>
                        </div>
                        <!-- Titre de l'article -->
                        <div class="card-title">
                            <b>{{tool.title}} </b>
                        </div>
                        <!-- Extrait de l'article -->
                        <div class="card-excerpt">
                            <p> {{tool.short_desc}} </p>
                        </div>
            
                    </div>
                    <!-- Fin du corp de notre carte -->
                </a>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

{%endblock content%}

outiltheque/toolbox/templates/toolbox/user_tools.html
{%extends 'toolbox/base.html'%}

{%block content%}


    <h3 class="mb-3"> Les outils de {{view.kwargs.username}} </h3>

    {%for tool in tools%}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{tool.owner.profile.image.url}}">
            <div class="madia-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{%url 'user-profile' tool.owner.id %}"> {{tool.owner}} </a>
                    <small class="text-muted">{{ tool.date_published|date:"d F Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'tool-detail' tool.id %}"> {{tool.title}} </a> </h2>
                <small class="text-muted"> Etat : {{tool.get_state_of_use_display}}</small>
                <p class="article-content"> {{tool.description}} </p>
            </div>
        </article>
    {%endfor%}
{%endblock content%}